import { Link } from 'react-router-dom'
import ChineseText from '../components/ChineseText.jsx'
import './ExamStrategiesPage.css'

const STRATEGIES = [
  { id:'listening',chinese:'听力',pinyin:'tīnglì',translation:'Listening',minutes:'3 мин',rule:'先看选项，再抓关系，不追每个词。',rulePinyin:'xiān kàn xuǎnxiàng, zài zhuā guānxì, bù zhuī měi ge cí',ruleTranslation:'Сначала варианты, затем отношения между фактами; не пытайся поймать каждое слово.',steps:['До аудио быстро найди различия между вариантами.','Во время записи лови кто / где / почему / результат.','После первого ответа не меняй его только из-за одного знакомого слова.']},
  { id:'reading',chinese:'阅读',pinyin:'yuèdú',translation:'Reading',minutes:'2–3 мин',rule:'先找题目要什么，再回原文定位。',rulePinyin:'xiān zhǎo tímù yào shénme, zài huí yuánwén dìngwèi',ruleTranslation:'Сначала пойми, что именно спрашивают, затем вернись в текст и найди опору.',steps:['Подчеркни в вопросе цель: причина, мнение, факт или главная мысль.','Ищи перефраз, а не только совпадающее слово.','Если два ответа похожи, выбери тот, который подтверждается текстом целиком.']},
  { id:'writing',chinese:'写作',pinyin:'xiězuò',translation:'Writing',minutes:'3–4 мин',rule:'先搭骨架，再检查语序。',rulePinyin:'xiān dā gǔjià, zài jiǎnchá yǔxù',ruleTranslation:'Сначала собери каркас предложения, потом проверяй порядок слов.',steps:['Найди сказуемое и кто выполняет действие.','Поставь время и место до основного глагола, если конструкция этого требует.','Отдельно проверь 把 / 被 / 得 / 地 / 的 и результативные дополнения.']},
  { id:'hskk',chinese:'口试',pinyin:'kǒushì',translation:'HSKK',minutes:'4 мин',rule:'不要停：结构比完美更重要。',rulePinyin:'bú yào tíng: jiégòu bǐ wánměi gèng zhòngyào',ruleTranslation:'Не останавливайся: структура ответа важнее попытки говорить идеально.',steps:['回答问题: позиция → причина → пример → вывод.','看图说话: кто/где → действие → детали → предположение.','Забыл слово — используй: 它是一种… / 它是用来…的 / 换句话说…']},
]

export default function ExamStrategiesPage(){return <main className="exam-strategies-page"><div className="exam-strategies-shell"><div className="exam-strategies-topbar"><Link to="/">← На главную</Link><Link to="/today">План на сегодня →</Link></div><header className="exam-strategies-hero"><p>应试技巧 · 2–4 МИНУТЫ НА ОДИН БЛОК</p><h1><ChineseText pinyin="yìngshì jìqiǎo" translation="Экзаменационные стратегии">应试技巧</ChineseText></h1><span>Короткие алгоритмы перед тренировкой или пробником. Это не теория курса, а напоминания, что делать под таймером.</span></header><div className="exam-strategies-grid">{STRATEGIES.map((item,index)=><article key={item.id}><div className="exam-strategy-number">0{index+1}</div><div className="exam-strategy-title"><h2><ChineseText pinyin={item.pinyin} translation={item.translation}>{item.chinese}</ChineseText></h2><b>{item.minutes}</b></div><div className="exam-strategy-rule"><ChineseText pinyin={item.rulePinyin} translation={item.ruleTranslation}>{item.rule}</ChineseText></div><ol>{item.steps.map((step)=><li key={step}>{step}</li>)}</ol></article>)}</div></div></main>}
